version: '3'
services:
  honeypot-template:
    container_name: honeypot-template
    build: .
    env_file:
      - .env
    ports:
      - "127.0.0.1:5000:5000" # Keep the 127.0.0.1:5000: segment to maintain the Action Workflow
